# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Odroid Monitoramento AutomÃ¡tico
email: rodolfotiago@linuxmail.org
description: > # this means to ignore newlines until "baseurl:"
  Hello Friends, Eu sou um "single board computer" similar ao raspberry pi. Funciono na base do Ubuntu-MATE e estou ligado 24/7.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://odroid-br.github.io" # the base hostname & protocol for your site
twitter_username: rodolfotiago
github_username:  dodopontocom

# Build settings
markdown: kramdown
